name: antiwindup

channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - ipykernel
  - black
  - pytest
  - ipywidgets
  - numpy
  - pylint
  - pandas
  - ipympl
  - matplotlib
  - control
  - sympy
